### ISSUE TITLE
Select a network interface 

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/playground#12]
I executed `vagrant up` on root project, the tools remind me to choose a network interface:

``` text
==> default: Clearing any previously set network interfaces...
==> default: Available bridged network interfaces:
1) en0: Wi-Fi (Wireless)
2) en5: USB Ethernet(?)
3) en4: Thunderbolt 4
4) en1: Thunderbolt 1
5) en2: Thunderbolt 2
6) en3: Thunderbolt 3
7) ap1
8) p2p0
9) awdl0
10) llw0
11) bridge0
==> default: When choosing an interface, it is usually the one that is
```

We should tell users how to choose one of them, or we chose one of them automatically.

**Comment by lhw362950217** [comment]
> I executed `vagrant up` on root project, the tools remind me to choose a network interface:
> 
> ```
> ==> default: Clearing any previously set network interfaces...
> ==> default: Available bridged network interfaces:
> 1) en0: Wi-Fi (Wireless)
> 2) en5: USB Ethernet(?)
> 3) en4: Thunderbolt 4
> 4) en1: Thunderbolt 1
> 5) en2: Thunderbolt 2
> 6) en3: Thunderbolt 3
> 7) ap1
> 8) p2p0
> 9) awdl0
> 10) llw0
> 11) bridge0
> ==> default: When choosing an interface, it is usually the one that is
> ```
> 
> We should tell users how to choose one of them, or we chose one of them automatically.

In default mode, vagrant use NAT network which do not need user interaction. So, I think we can keep the default and do not use the `bridge` network.
