### ISSUE TITLE
/home/vagrant/desktop/sqlflow/docker/dev/find_fastest_resources.sh is missing while running vagrant provision.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/playground#19]
Run command `vagrant up` at the first time, or run `vagrant provision` after the VM is created. We will get the following error:

```TXT
==> default: Running provisioner: shell...
    default: Running: /var/folders/nz/g2f2658s68j59vqvspnxk6wc0000gn/T/vagrant-shell20200531-32506-188g10.bash
    default: /tmp/vagrant-shell: line 8: /home/vagrant/desktop/sqlflow/docker/dev/find_fastest_resources.sh: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by brightcoder01** [comment]
```
git clone --recursive https://github.com/sql-machine-learning/playground.git
```
or
```
git clone https://github.com/sql-machine-learning/playground.git
cd playground
git submodule init
git submodule update
```

We can add more description about these steps so that users/developers can set up smoothly.

**Comment by lhw362950217** [comment]
> ```
> git clone --recursive https://github.com/sql-machine-learning/playground.git
> ```
> 
> or
> 
> ```
> git clone https://github.com/sql-machine-learning/playground.git
> cd playground
> git submodule init
> git submodule update
> ```
> 
> We can add more description about these steps so that users/developers can set up smoothly.

Yes, we need to update the `sqlflow` submodule before we can play.
