### ISSUE TITLE
ImageInspectError

### ISSUE THREAD

**Issue by cygu-ai** [sql-machine-learning/playground#34]
Hello ! and Good luck :-) i'm here if any questions

1./ run describe iris.train in the first cell of iris-dnn.ipynb

2./ go to the associated argo workflow log

Actual: ImageInspectError: Failed to inspect image "sqlflow/sqlflow:step": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2/l: invalid argument

and the cmd seems to never ending 

nota: I change the jupyter IP to 127.0.0.1 otherwise I can't access it from Host ( W10 )

![argo](https://user-images.githubusercontent.com/61332073/84314779-ef6bf680-ab68-11ea-9d17-268bf12de496.png)
![jupyter](https://user-images.githubusercontent.com/61332073/84314783-f1ce5080-ab68-11ea-86a2-e6fb154e9b04.png)
![cmd](https://user-images.githubusercontent.com/61332073/84315100-75883d00-ab69-11ea-800f-c623d7de29cd.png)

**Comment by lhw362950217** [comment]
@asm-cygu Nice to see u :)
I'm very glad that you are playing SQLFlow playground.

It seems k8s could not load the `sqlflow/sqlflow:step` image normally. This image is the one who does the real ML training work. Here are some suggestions:
- use `docker images` command to check if the image `sqlflow/sqlflow:step` is exist
- maybe use `docker image rm  sqlflow/sqlflow:step` to remove the image and pull it again with `docker pull sqlflow/sqlflow:step`
- check your vm to see if the disk space is full
- refer to [stackoverflow](https://stackoverflow.com/questions/55334380/error-readlink-var-lib-docker-overlay2-invalid-argument) to see if it matches your problem

**Comment by cygu-ai** [comment]
Same issue for the 3 first clues :-], I will have to read the stackoverflow post ( and try the following cmd 
docker system prune --all
docker volume prune 
docker-compose up )

All work for you I imagine ?

[psafx.txt](https://github.com/sql-machine-learning/playground/files/4769704/psafx.txt)
![df-h](https://user-images.githubusercontent.com/61332073/84483676-fc3c3780-ac99-11ea-84de-dbcf6fc9c808.png)
![dockerimages](https://user-images.githubusercontent.com/61332073/84483681-fd6d6480-ac99-11ea-9dcf-e38b7b7d59f0.png)
![dockerls](https://user-images.githubusercontent.com/61332073/84483682-fe05fb00-ac99-11ea-8b53-f958e6db2add.png)
![dockerpull](https://user-images.githubusercontent.com/61332073/84483683-fe05fb00-ac99-11ea-800c-d628be31c924.png)

**Comment by cygu-ai** [comment]
After the cmd
docker system prune --all
docker volume prune 

seems to affect the vagrant box ;-p , I will try to restart all from fresh install later ;-) 

![result](https://user-images.githubusercontent.com/61332073/84486379-a073ad80-ac9d-11ea-9e35-8d1538d2befd.png)

**Comment by cygu-ai** [comment]
Fresh install do the trick !

Good job I will try it later :-p !

![jupytersuccess](https://user-images.githubusercontent.com/61332073/84488280-40323b00-aca0-11ea-8227-291fea901c62.png)
![argosuccess](https://user-images.githubusercontent.com/61332073/84488282-41636800-aca0-11ea-9098-87b9d70d42f6.png)
