### ISSUE TITLE
 NameError: name 'sqlflow_models' is not defined with sqlflow_models.AutoClassifier

### ISSUE THREAD

**Issue by cygu-ai** [sql-machine-learning/playground#38]
Hello ! first cells run great ! just a miss with AutoClassifier I guess :-) 

**Code sample:**
%%sqlflow
SELECT * FROM iris.train TO TRAIN sqlflow_models.AutoClassifier WITH
  model.n_classes = 3,
  train.epoch = 10
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class
INTO sqlflow_models.my_dnn_model;

**Result in argo:**
==========Output==========

Traceback (most recent call last):

  File "<stdin>", line 138, in <module>

  File "/opt/sqlflow/python/sqlflow_submitter/tensorflow/train.py", line 75, in train

    estimator = eval(estimator_string)

  File "<string>", line 1, in <module>

NameError: name 'sqlflow_models' is not defined

**Comment by lhw362950217** [comment]
Please pull the latest code, we have imported the latest `sqlflow_models`, this problem is fixed.
